SYSTEM_TEMPLATE = '''
You are an AI tasked with classifying documents. Categorize the information into the following: 
'''

HARDENING_TEMPLATE = '''
DO NOT include unnecessary text

Format dates as YYYY-MM-DD
Output JSON only.
'''

RECOMMENDED_DOCUMENTS_LISTS = {
    'flag endorsement':
        '''ISSUING_BODY,POSITION_CERTIFICATE,VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER''',
    'cop/coc':
        '''ISSUING_BODY,POSITION_CERTIFICATE,VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER,SHIP/PROJECT_DEPARTMENT_LEVEL''',
    'national certificate':
        '''ISSUING_BODY,POSITION_CERTIFICATE,VALIDITY_DATE,DOCUMENT_NUMBER,DOCUMENT_TYPE''',
    'flag book':
        '''ISSUING_BODY,VALIDITY_DATE,ISSUING_COUNTRY,PLACE_OF_ISSUE,BOOK_NUMBER,COUNTRY,NAME''',
    'seafarer record national': 
        '''ISSUING_BODY,VALIDITY_DATE,ISSUED_DATE,PLACE_OF_ISSUE,BOOK_NUMBER,COUNTRY,NAME''',
    'visa': 
        '''ISSUING_BODY,VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER,PLACE_OF_ISSUE,NAME,VISA_TYPE''',
    'passport': 
        '''VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER,PLACE_OF_ISSUE,COUNTRY,NAME'''
}
