SYSTEM_TEMPLATE = '''
You are an AI tasked with classifying documents. Categorize the information into the following: 
'''

HARDENING_TEMPLATE = '''
DO NOT include unnecessary text
DO NOT output the word json

Format dates as YYYY-MM-DD
Output JSON only.
'''

RECOMMENDED_DOCUMENTS_LISTS = {
    'flag endorsement':
        '''ISSUING_BODY,POSITION_CERTIFICATE,VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER''',
    'cop/coc':
        '''ISSUING_BODY,POSITION_CERTIFICATE,VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER,SHIP/PROJECT_DEPARTMENT_LEVEL''',
    'national certificate':
        '''ISSUING_BODY,POSITION_CERTIFICATE,VALIDITY_DATE,DOCUMENT_NUMBER,DOCUMENT_TYPE''',
    'flag book':
        '''ISSUING_BODY,VALIDITY_DATE,ISSUING_COUNTRY,PLACE_OF_ISSUE,BOOK_NUMBER,COUNTRY,LAST_NAME,MIDDLE_NAME,FIRST_NAME''',
    'seamans book': 
        '''ISSUING_BODY,VALIDITY_DATE,ISSUED_DATE,PLACE_OF_ISSUE,BOOK_NUMBER,COUNTRY,LAST_NAME,FIRST_NAME''',
    'visa': 
        '''ISSUING_BODY,VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER,PLACE_OF_ISSUE,LAST_NAME,MIDDLE_NAME,FIRST_NAME,VISA_TYPE''',
    'passport': 
        '''VALIDITY_DATE,ISSUED_DATE,DOCUMENT_NUMBER,PLACE_OF_ISSUE,COUNTRY,LAST_NAME,MIDDLE_NAME,FIRST_NAME'''
}
