name: Solus+ Docs Parser Integrations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  django:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run Migrations
      run: |
        cd backend
        python manage.py migrate --check

    - name: Run Linting
      run: |
        pip install flake8
        flake8 backend --count --show-source --statistics

    - name: Check Code Formatting
      run: |
        pip install black
        black --check backend

    - name: Run Security Scan
      run: |
        pip install bandit
        bandit -r backend

    - name: Django System Check
      run: |
        cd backend
        python manage.py check

    - name: Collect Static Files
      run: |
        cd backend
        python manage.py collectstatic --noinput

    - name: Run API Tests
      run: |
        pip install pytest pytest-django
        pytest backend
